service: trading-service
name: trader-bot
provider:
    name: aws
    runtime: nodejs10.x
    region: eu-north-1
functions:
    trade-api:
        handler: handler.trade_api
        events:
            - http: ANY /
            - http: "ANY {proxy+}"
package:
    excludeDevDependencies: false
plugins:
    - serverless-offline
